<?php

function dkc_perm_permission() {
  return array(
    'manually_set_department' => array(
      'title' => t('Manually set department'),
      'description' => t('Allows users to manually set their department'),
    ),
  );
}

function dkc_perm_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'department_content_node_form':
      // Check the permission we created earlier.
      if (!user_access('manually_set_department')) {
        global $user;
        // Load the users account.
        $account = user_load($user->uid);
        $node_department = field_get_items('node', $form['#node'], 'field_department');
        $user_in_node_department = false;
        $user_department = isset($account->field_department[LANGUAGE_NONE][0]) ? $account->field_department[LANGUAGE_NONE][0]['tid'] : FALSE;

        if (isset($account->field_multiple_department_manage[LANGUAGE_NONE][0]['tid']) && in_array('multiple department manager', $account->roles)) {
          foreach ($account->field_multiple_department_manage[LANGUAGE_NONE] as $user_multiple_department ) {
            if ($node_department[0]['tid'] == $user_multiple_department['tid']) {
              $user_in_node_department = true;
            }
          }
        }

        if ($user_department == $node_department[0]['tid']) {
          $user_in_node_department = true;
        }

        if ($node_department !== FALSE && !$user_in_node_department) {
          $form['#disabled'] = 1;
          drupal_set_message('You don\'t have access to edit this content. Please contact your administrator.', 'error');
        }
        else {

          // Get their department tid.
          $field_department_tid = $account->field_department[LANGUAGE_NONE][0]['tid'];

          foreach ($form['field_department'][LANGUAGE_NONE]['#options'] as $k => $v) {
            $unset_option = true;
            if (in_array('multiple department manager', $account->roles)) {
              foreach($account->field_multiple_department_manage[LANGUAGE_NONE] as $deparment_tid) {
                if ($k == $deparment_tid['tid']) {
                  $unset_option = false;
                }
              }
            }
            if ($k == $field_department_tid) {
              $unset_option = false;
            }
            if ($unset_option) {
              // Unset any but their own departments.
              unset($form['field_department'][LANGUAGE_NONE]['#options'][$k]);
            }
          }
        }
      }
      break;
  }
}

/**
 * Access callback function
 */

function _dkc_perm_access() {
  global $user;
  $user_entity = user_load($user->uid);

  if (arg(0) == 'admin' && arg(1) == 'structure' && arg(2) == 'menu' && arg(3) == 'manage'
    && (in_array('department manager', $user_entity->roles) || in_array('department administrator', $user_entity->roles) || in_array('multiple department manager', $user_entity->roles))) {
    // $user_department = $user_entity->field_department[LANGUAGE_NONE][0]['tid'];
    // $user_menu_department = $user_entity->field_menu_to_manage[LANGUAGE_NONE][0]['menureference'];
    $menu_accessed = arg(4);

    $access = FALSE;
    if (in_array('multiple department manager', $user_entity->roles) && isset($user_entity->field_menu_to_manage[LANGUAGE_NONE][0]['menureference'])) {
      foreach ($user_entity->field_menu_to_manage[LANGUAGE_NONE] as $user_menu_department) {
        if ($user_menu_department['menureference'] == $menu_accessed) {
          $access = TRUE;
        }
      }
    }

    return $access;
  }

  if (in_array('administrator', $user_entity->roles)) {
    return TRUE;
  }
}

/**
 * Implements hook_menu_admin_per_menu_perm_menus_alter().
 */
function dkc_perm_menu_admin_per_menu_perm_menus_alter(&$perm_menus, $account) {
  // Override menu permissions based on value of "menu to manage" field in user's profile.
  $perm_menus = array();
  $user_entity = user_load($account->uid);

  // $user_menu_department = isset($user_entity->field_menu_to_manage[LANGUAGE_NONE][0]['menureference']) ? $user_entity->field_menu_to_manage[LANGUAGE_NONE][0]['menureference'] : FALSE;

  $menus = menu_get_menus();
  foreach ($menus as $name => $title) {
    if (isset($user_entity->field_menu_to_manage[LANGUAGE_NONE][0]['menureference'])) {
      foreach ($user_entity->field_menu_to_manage[LANGUAGE_NONE] as $user_menu_department) {
        if (user_access('administer ' . $name . ' menu items', $account) && $name == $user_menu_department['menureference'] ) {
          $perm_menus[$name] = $name;
        }
      }
    }
  }
}