block.settings.hycm_blocks_black:
  type: block_settings
  label: 'Black block'
  mapping:
    foo:
      type: string
      label: Foo
##type: mapping
##  label: 'Format text'
##  maping:
##    value:
##      type: text
##      label: 'Value'
##    format:
##      type: string
##      label: 'Format'

block.settings.hycm_blocks_vpsrequest:
  type: block_settings
  label: 'VPS Request'
  mapping:
    request:
      type: text
      label: 'Confirm text'
    confirm:
      type: text
      label: 'Confirm text'
    request_title:
      type: text
      label: 'Popup label (request)'
    confirm_title:
      type: text
      label: 'Popup label (confirm)'
  after_text:
    type: text
    label: 'Popup label (confirm)'
block.settings.hycm_blocks_mainmenu:
  type: block_settings
  label: 'MainMenu block'
  mapping:
    foo:
      type: string
      label: Foo

block.settings.hycm_blocks_notfound:
  type: block_settings
  label: 'Not found block'
  mapping:
    text:
      type: text
      label: '404 Text'

block.settings.hycm_blocks_openaccount:
  type: block_settings
  label: 'Open an Account'
  mapping:
    link_text:
      type: string
      label: 'Link text'

block.settings.hycm_blocks_markets_home:
  type: block_settings
  label: 'Markets (home) block'
  mapping:
    foo:
      type: string
      label: Foo

markets_item:
  type: config_object
  mapping:
    name:
      type: text
      label: 'Name'
    title:
      type: text
      label: 'Title'
    description:
      type: text
      label: 'Description'
    max_leverage:
      type: string
      label: 'Maximum leverage'
    max_leverage_eu:
      type: string
      label: 'Maximum leverage (.eu & .co.uk)'
    spreads:
      type: string
      label: 'Spreads'
    spreads_eu:
      type: string
      label: 'Spreads (eu)'
    margins:
      type: string
      label: 'Margins'
    margins_eu:
      type: string
      label: 'Margins (eu)'
    market_id:
      type: string
      label: 'Market ID'

hycm_blocks.marketscontent:
  type: config_object
  mapping:
    forex:
      type: markets_item
    stocks:
      type: markets_item
    indices:
      type: markets_item
    cryptocurrencies:
      type: markets_item
    commodities:
      type: markets_item

hycm_blocks.frequently_asked_questions:
  type: config_object
  mapping:
    faqs:
      type: sequence
      label: 'FAQs'
      sequence:
        type: hycm.frequently_asked_questions

hycm.frequently_asked_questions:
  type: config_object
  mapping:
    question:
      type: text
      label: 'Question'
    answer:
      type: text
      label: 'Answer'

hycm.award:
  type: config_object
  mapping:
    label:
      type: text
      label: 'Label'
    content:
      type: text
      label: 'Content'

hycm_blocks.awards:
  type: config_object
  mapping:
    items:
      type: sequence
      label: 'Items'
      sequence:
        type: hycm.award
