<?php
/**
 * @file
 * Code for the DKC sidebar feature.
 */

include_once 'dkc_sidebar.features.inc';

/**
 * @file
 * Represents hook definition and main function.
 */

/**
 * Implements hook_menu().
 */
function dkc_sidebar_menu() {
  $items = array();

  $items['admin/config/dkc/sidebar'] = array(
    'title' => 'DKC Sidebar images',
    'description' => 'DKC Sidebar images settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dkc_sidebar_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'dkc_sidebar.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function dkc_sidebar_theme($existing, $type, $theme, $path) {
  return array(
    'dkc_sidebar_images' => array(
      'variables' => array('settings' => NULL),
    ),
    'dkc_sidebar_cards' => array(
      'variables' => array(
        'title' => NULL,
        'subtitle' => NULL,
        'image' => NULL,
        'footer' => NULL,
      ),
      'template' => 'templates/dkc_sidebar_cards',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function dkc_sidebar_block_info() {
  $blocks = array();

  $blocks['sidebar_images'] = array(
    'info' => t('Sidebar images'),
    'status' => 0,
    'weight' => 100,
    'cache' => DRUPAL_CACHE_PER_PAGE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'taxation/tax-commissioner',
  );

  $blocks['sidebar_cards'] = array(
    'info' => t('Sidebar cards logos'),
    'status' => 0,
    'weight' => 101,
    'cache' => DRUPAL_CACHE_PER_PAGE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => "taxation/property-tax\ntaxation/tax-sales-general-information\ntaxation/property-tax/*\ntaxation/tax-sales-general-information/*",
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dkc_sidebar_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'sidebar_images':
      $settings = variable_get('dkc_sidebar_settings', array());
      $block['content'] = array(
        '#markup' => theme('dkc_sidebar_images', array('settings' => $settings)),
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'dkc_sidebar') . '/css/dkc_sidebar.css',
          ),
        ),
      );
      break;

    case 'sidebar_cards':
      $src = '';
      $image = variable_get('dkc_sidebar_cards', NULL);
      if (!empty($image)) {
		//  echo "<pre>"; print_r($image); die;
        $image = file_load($image);
        $src = image_style_url('dkc_sidebar_images', $image->uri);
      }
      $params = array(
        'title' => t('Property Tax Online'),
        'subtitle' => t('Payment Forms Accepted'),
        'image' => $src,
        'footer' => array(
          "Debit / Credit Fee = 2.35%",
          "E-Check Fee = FREE",
        ),
      );

      $block['content'] = array(
        '#markup' => theme('dkc_sidebar_cards', $params),
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'dkc_sidebar') . '/css/dkc_sidebar.css',
          ),
        ),
      );
      break;
  }

  return $block;
}

/**
 * Custom theme handler for generating html of sidebar images.
 */
function theme_dkc_sidebar_images(&$variables) {
  $settings = $variables['settings'];
  $output = '';
  foreach ($settings as $setting) {
    list($image, $url) = array_values($setting);
    $src = '';
    if (!empty($image)) {
      $image = file_load($image);
      $src = image_style_url('dkc_sidebar_images', $image->uri);
    }
    $output .= '<div class="dkc-sidebar-image">';
    $output .= "<a href='{$url}' target='_blank'>";
    $output .= "<img src='{$src}'>";
    $output .= "</a>";
    $output .= '</div>';
  }
  return $output;
}
