block.settings.hycm_landing_pages_wed_webinar:
  type: block_settings
  label: 'Wed Webinar block'
  mapping:
    header:
      type: mapping
      label: Header
      mapping:
        subtitle:
          type: text
          label: Subtitle
        title:
          type: text
          label: Title
        webinar_time:
          type: text
          label: Time
        duration:
          type: text
          label: Duration
        btn_label:
          type: text
          label: 'Button label'
    top_left:
      type: mapping
      label: 'Top left'
      mapping:
        title:
          type: text
          label: Time
        content:
          type: text
          label: Duration
    top_right:
      type: mapping
      label: 'Top right'
      mapping:
        title:
          type: text
          label: Time
        content:
          type: text
          label: Duration

    bottom_left:
      type: mapping
      label: 'Bottom left'
      mapping:
        title:
          type: text
          label: Time
        content:
          type: text
          label: Duration
    bottom_right:
      type: mapping
      label: 'Bottom right'
      mapping:
        title:
          type: text
          label: Time

block.settings.shortform_block:
  type: block_settings
  label: 'ShortForm Block'
  mapping:
    title_form:
      type: string
      label: 'Title Form'